Repository honestbank/kp, pull requests merged in 2022-12, with the labels that each got.

#52 feat: convert everything to middleware
  v2/interface.go
  v2/internal/consumer/consumer.go
  v2/kafkaheaders/set_test.go
  v2/kp.go
  v2/kp_example_test.go
  v2/kp_test.go
  v2/middlewares/consumer/consumer.go
  v2/middlewares/consumer/consumer_test.go
  v2/middlewares/deadletter/deadletter.go
  v2/middlewares/deadletter/deadletter_test.go
  v2/middlewares/interface.go
  v2/middlewares/retry/retry.go
  v2/middlewares/retry/retry_test.go
Labels: size/XL

#53 fix: make consumer package available
  v2/consumer/consumer.go
  v2/consumer/consumer_test.go
  v2/consumer/types.go
  v2/kp_example_test.go
  v2/kp_test.go
  v2/middlewares/consumer/consumer.go
Labels: size/XS

#56 docs: add code of conduct file
  CODE_OF_CONDUCT.md
Labels: size/L

#55 chore: add license
  LICENSE.md
Labels: size/L

#54 docs: add documentation for the latest api
  .github/workflows/shiftleft-go.yaml
  CODE_OF_CONDUCT.md
  LICENSE.md
  contributing.md
  docs/docs/contributing/contributing.md
  docs/docs/features/consumer.md
  docs/docs/features/deadletters.md
  docs/docs/features/retries.md
  docs/docs/introduction/concepts.md
  docs/docs/introduction/getting-started.md
  docs/docs/introduction/why-use-kp.md
  docs/docs/middlewares/backoff.md
  docs/docs/middlewares/consumer.md
  docs/docs/middlewares/custom-middleware.md
  docs/docs/middlewares/deadletter.md
  docs/docs/middlewares/introduction.md
  docs/docs/middlewares/metrics.md
  docs/docs/middlewares/retry.md
  docs/docs/middlewares/retrycounter.md
  docs/docs/middlewares/tracing.md
Labels: size/XXL

#59 docs: add security policy
  SECURITY.md
Labels: size/S

#58 docs: add algolia integration
  SECURITY.md
  docs/docusaurus.config.js
Labels: size/M

#62 docs: add issue and pr templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: size/M

#60 docs: move contributing files
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  contributing.md
  docs/docs/contributing/contributing.md
Labels: size/L
