Repository honestbank/kp, pull requests merged in 2022-10, with the labels that each got.

#13 fix: remove logging of claimed message
  .github/workflows/build.yaml
  consumer.go
  examples/simple/go.mod
  examples/simple/go.sum
  examples/simple/main.go
  examples/simple_backoff/go.mod
  examples/simple_backoff/go.sum
  examples/simple_backoff/main.go
  go.mod
  go.sum
Labels: size/S

#14 fix: add suffix to consumer group name
  kp.go
Labels: size/XS

#15 fix: remove logging and update unit test
  consumer.go
  consumer_test.go
  examples/simple/main.go
  go.mod
  go.sum
  interface.go
  kp.go
  kp_test.go
Labels: size/L

#16 feat: add producer
  .github/workflows/build.yaml
  v2/docker-compose.yaml
  v2/go.mod
  v2/go.sum
  v2/internal/config/config.go
  v2/internal/config/config_test.go
  v2/internal/schemaregistry/client.go
  v2/internal/schemaregistry/client_test.go
  v2/internal/schemaregistry/config.go
  v2/internal/serialization/benchmark_test.go
  v2/internal/serialization/decoder.go
  v2/internal/serialization/encoder.go
  v2/internal/serialization/serialization_test.go
  v2/producer/producer.go
  v2/producer/producer_benchmark_test.go
  v2/producer/producer_integration_test_remote_test.go
  v2/producer/producer_test.go
  v2/producer/types.go
Labels: size/XL, hacktoberfest-accepted

#17 chore: add consumer api and count util
  .github/workflows/build.yaml
  v2/go.mod
  v2/go.sum
  v2/internal/config/config.go
  v2/internal/config/config_test.go
  v2/internal/consumer/consumer.go
  v2/internal/consumer/consumer_test.go
  v2/internal/consumer/types.go
  v2/internal/retrycounter/counter.go
  v2/internal/retrycounter/counter_test.go
  v2/internal/serialization/serialization_test.go
  v2/producer/producer.go
  v2/producer/producer_test.go
  v2/producer/types.go
Labels: size/L

#18 feat: add kp v2 API
  kp_test.go
  mocks/mock_kpprocessor.go
  v2/interface.go
  v2/internal/consumer/consumer_test.go
  v2/internal/retrycounter/counter.go
  v2/internal/retrycounter/counter_test.go
  v2/kp.go
  v2/kp_test.go
  v2/producer/producer.go
Labels: size/L
