Repository honestbank/kp, pull requests merged in 2023-01, with the labels that each got.

#63 feat: upgrade sarama
  .github/workflows/build.yaml
  .github/workflows/shiftleft-go.yaml
  .github/workflows/trivy_scan.yaml
  docs/package-lock.json
  examples/simple/go.mod
  examples/simple_backoff/go.mod
  go.mod
  go.sum
Labels: size/XL

#65 fix: Update the package integrity
  .github/workflows/build.yaml
  docs/package-lock.json
Labels: size/XS

#66 docs: add a migration guide
  docs/docs/migration/_category_.json
  docs/docs/migration/migration.md
Labels: size/S

#68 fix: race condition
  .idea/kp.iml
  .idea/modules.xml
  .pre-commit-config.yaml
  catalog-info.yaml
  docs/package-lock.json
  docs/package.json
  v2/kp.go
Labels: size/S
